### ISSUE TITLE
MGN12 Carriage does not lay flat on Tap_Center

### ISSUE THREAD

**Issue by joseph-greiner** [VoronDesign/Voron-Tap#15]
I was looking at the CAD for the Tap an noticed interference between the MGN12 carriage and the tap_center component. I printed the STL in the repo, mounted the carriage with the belts installed and noticed that the parts mount at a slight angle to each other. 

![tap_center_released](https://user-images.githubusercontent.com/11715110/204206221-743428fa-b5f0-46b3-a491-f788878e3677.jpg)

The issue is that the chamfer for the bottom of the carriage on the tap_center part is too big and will not let the carriage lay flat, even with belts installed.

![compare](https://user-images.githubusercontent.com/11715110/204206961-f950eac4-e634-4703-b934-62bd7431e5d4.png)

By cutting out the large chamfer and adding a 0.4mm chamfer to the area the carriage now lays flat.

![tap_center_fixed](https://user-images.githubusercontent.com/11715110/204207214-9647deda-944d-43bc-b1d2-cebbfc25ff51.jpg)

Modified STL and STEP files can be provided if requested.

**Comment by Badnoob-327** [comment]
it appears that some MGN12's have a different chamfor spec than others, I will update the STL.

**Comment by Badnoob-327** [comment]
> I was looking at the CAD for the Tap an noticed interference between the MGN12 carriage and the tap_center component. I printed the STL in the repo, mounted the carriage with the belts installed and noticed that the parts mount at a slight angle to each other.
> 
> ![tap_center_released](https://user-images.githubusercontent.com/11715110/204206221-743428fa-b5f0-46b3-a491-f788878e3677.jpg)
> 
> The issue is that the chamfer for the bottom of the carriage on the tap_center part is too big and will not let the carriage lay flat, even with belts installed.
> 
> ![compare](https://user-images.githubusercontent.com/11715110/204206961-f950eac4-e634-4703-b934-62bd7431e5d4.png)
> 
> By cutting out the large chamfer and adding a 0.4mm chamfer to the area the carriage now lays flat.
> 
> ![tap_center_fixed](https://user-images.githubusercontent.com/11715110/204207214-9647deda-944d-43bc-b1d2-cebbfc25ff51.jpg)
> 
> Modified STL and STEP files can be provided if requested.

please look at the updated tap_center_r2 file and let me know if you see need for more than that, I like to keep some chamfer there if possible

**Comment by joseph-greiner** [comment]
I am printing it now, I will update when it is finished, but the support was not exported with the part STL.

![no_support](https://user-images.githubusercontent.com/11715110/204456531-bcec755c-bfe7-4ed0-8f79-4fc66a725e8f.png)

**Comment by joseph-greiner** [comment]
Printed the r2 STL, the carriage sits flat now.

![rev2_printed](https://user-images.githubusercontent.com/11715110/204478792-c9d99bf1-c79f-4559-85ae-cebc84899c4e.jpg)

**Comment by Badnoob-327** [comment]
I think this can be closed now, thank you for your feedback.
