### ISSUE TITLE
Wrong link to "Tap-Klipper Instructions"

### ISSUE THREAD

**Issue by GuidoHendriks** [VoronDesign/Voron-Tap#19]
First things first; I'm so impressed with this project! Thanks a lot. 👍🏻 

---

Now the minor issue with the manual...

On page 37 of the manual it says:

> The software setup and other initial setup steps with your new printer can also be found on our documentation page. We recommend starting with the **Tap-Klipper Instructions** on our Github.

This contains a wrong link.

Have double checked that I have the latest file. Also noticed this https://github.com/VoronDesign/Voron-Tap/issues/14 which also does not seem to be fixed in the latest file. Maybe it's not committed or pushed to Github yet?

**Comment by Badnoob-327** [comment]
got it , and I rerefixed the #14, appreciate the reminder.

**Comment by nemgrea** [comment]
fixed via https://github.com/VoronDesign/Voron-Tap/pull/32
