### ISSUE TITLE
Typo in manual about BOM heatset inserts

### ISSUE THREAD

**Issue by contrapuntal** [VoronDesign/Voron-Tap#23]
In the BOM on pg15: "These are standard Voron inserts, 4.7 mm diameter and 4mm tall"

4.7mm refers to the hole size in CAD. Voron standard threaded inserts are 5mm diameter.

**Comment by Badnoob-327** [comment]
you are absolutely correct. thank you!

**Comment by nemgrea** [comment]
fixed via https://github.com/VoronDesign/Voron-Tap/pull/32
