### ISSUE TITLE
Brass threaded insert causing magnet not to sit flush

### ISSUE THREAD

**Issue by contrapuntal** [VoronDesign/Voron-Tap#24]
A M3x5x4 threaded insert causes bulging in the magnet holder, so that the magnet won't sit flush. 
![PC100016](https://user-images.githubusercontent.com/16892776/206875507-b3fe6c4f-5ca0-44ee-9ae9-d50b5dcbaca5.JPG)

**Comment by mrmultifunk** [comment]
I had this happening as well. What worked for me, was to reheat the insert and press the bulging down with an Allen key.

**Comment by krankydonkey** [comment]
What I found worked was inserting the magnet first and then putting the heat set insert in while holding the magnet flush with the side with a ruler

**Comment by Badnoob-327** [comment]
I think krankydonkey has a good idea, and we can fix that in documentation (by switching the order and doing magnets before heatets.

**Comment by Badnoob-327** [comment]
Next manual has the order of operations switched (magnets in first, then inserts), so this should be fine

**Comment by ps-bond** [comment]
> Next manual has the order of operations switched (magnets in first, then inserts), so this should be fine

Is there an issue with breaking the adhesive if that's done?  My usual way of releasing superglued parts is to warm them...

**Comment by Badnoob-327** [comment]
I've not had any issues with the superglue getting loose here, if you wish you could try RTV instead of superglue.

**Comment by ps-bond** [comment]
Actually I've been using Loctite 480...  I've been using the stuff for a while to glue magnets to prints and have found it more resilient than standard CA.  Probably overkill, admittedly.

**Comment by nemgrea** [comment]
fixed via https://github.com/VoronDesign/Voron-Tap/pull/32
