### ISSUE TITLE
klipper config instruction should instruct the user to remove position_endstop

### ISSUE THREAD

**Issue by MapleLeafMakers** [VoronDesign/Voron-Tap#26]
When using probe as a virtual endstop, the `position_endstop` setting for stepper_z needs to be removed / commented out.  this should be called out in the instructions.

**Comment by KiloQubit** [comment]
It is already called out in the instructions
<img width="1044" alt="Screen Shot 2022-12-12 at 11 02 31" src="https://user-images.githubusercontent.com/69389593/207093645-5c244c2d-484c-4eac-8c99-cccc95873d13.png">

**Comment by MapleLeafMakers** [comment]
Apologies, I don't know how I missed that
