### ISSUE TITLE
Opb961 + electric components fix for manual

### ISSUE THREAD

**Issue by artemen** [VoronDesign/Voron-Tap#28]
Not all listed opb sensors have color coded wires, for example opb961 has only pins. 
Page 13 right hand side picture is really confusing - at first it looks just like the opb sensor view from the button, and if connecting based solely on the looks (very natural given how the rest of the manual is very visual) one can burn mcu.  
If just assume that the view is from the bottom it's pretty harmless and just won't work, however if you compare it to the schematic and see that cathode and anode pins are switched in the picture one can assume that it's the view from the top, this will result in short circuiting of the 5v rail on the mcu. 
The truth is that page13 picture is neither the top nor the bottom view, but rather a diagram with pins rearranged to make it look neater. 
Either include a warning that the picture below is a diagram, or adjust it to make it look as the most useful view- from the bottom. 

![Screenshot_20221214-004926](https://user-images.githubusercontent.com/7785111/207558537-ff62c663-4232-4fe4-a747-939efb09ae5d.png)
![Screenshot_20221214-013048](https://user-images.githubusercontent.com/7785111/207558767-f6179cd3-e410-41c1-9e13-5297919b28d1.png)

**Comment by Badnoob-327** [comment]
Hi, thanks for your comment.  OPB 961 is not a recommended sensor for the Wired option, as it has only pins.  The only wired sensors I have recommended are OPB 991 P51Z , OPB 991 L51Z, OPB 991 T51Z, OPB 991 T11Z
