### ISSUE TITLE
Documentation: X endstop should be shown in different orientation

### ISSUE THREAD

**Issue by top-gun** [VoronDesign/Voron-Tap#31]
Hi,

I use an X-endstop mounted to the toolhead. In my case it's a KW11, but I saw the same issue with an Omron D2F-L on Discord.

The documentation (page 30) shows the endstop with the latch opening to the bottom. Due to the shape of the XY-joiner, the endstop will not trigger in this orientation. With the endstop mounted in reverse position (latch opening to the top), it will hit the XY-joiner reliably.

I think the documentation should show the endstop with the latch opening to the top so people use the working position.

**Comment by ditdafivo** [comment]
For me, even flipping it upside down didn't trigger. I ended up gluing a piece of plastic onto the XY Joint, through on discord someone suggested that bending the lever a little might have been enough.

**Comment by hyperphonic0** [comment]
The current Trident CAD shows it in the described orientation.

<img width="750" alt="trident-x-carriage" src="https://user-images.githubusercontent.com/68255713/209480635-55174bb5-edf8-44a1-a748-7b460da3952a.png">

**Comment by W141-ID** [comment]
@ditdafivo had/have the same issue. As you suggested I bented the lever which ended up in breaking it's plastic guard, but it seems to work for now.
Just to be clear, lever is still on, just the lever guard has broken off. Now it can make a 45deg turn.

**Comment by top-gun** [comment]
Fixed as of Center part R6.
