### ISSUE TITLE
Center void on magnet holders different sizes.

### ISSUE THREAD

**Issue by blgli** [VoronDesign/Voron-Tap#35]
The circle indentations that were added to Tap_Magnet_Left_r1 and Tap_Magnet_Right_r1, are different depths.

Not sure which is correct but on Tap_Magnet_Left_r1 it is 0.2mm deep and on Tap_Magnet_Right_r1 it is 0.1mm deep, also these STL's are not included in the latest CAD.

**Comment by Badnoob-327** [comment]
Hi, thanks for pointing this out.  Those indentations were temporary features to help align the magnets for manual images.  They are not needed and are not in the current CAD, I'll update the STLs to remove them, but there should be no effect on performance.
