### ISSUE TITLE
Chamfer in hole

### ISSUE THREAD

**Issue by Lelle79** [VoronDesign/Voron-Tap#38]
I have a chamfer in the angled holes for bolting "tap upper" to "tap front". is that supposed to be there? the slicer picture is upside down. sorry for that.

![2022-12-22](https://user-images.githubusercontent.com/121227986/209111307-ce87315e-9e92-4efd-8494-0913f8546a75.png)
![2022-12-22 (1)](https://user-images.githubusercontent.com/121227986/209111330-a0ab6aec-c9f2-4d47-941e-d8c556564db8.png)

**Comment by nemgrea** [comment]
that feature is to prevent the slicer from creating overhung bridges in that area. your image shows the part being sliced in the in correct direction. in real life the parts bolt up just fine, the funky cad feature is just to force a specific behavior from the slicer
