### ISSUE TITLE
(small) Error in the Assembly Manual

### ISSUE THREAD

**Issue by laserbeak** [VoronDesign/Voron-Tap#7]
Hi,
Just wanted to point out a small error in the assembly manual. An unfinished sentence(or did I miss the punchline?).
![image](https://user-images.githubusercontent.com/3384800/204151997-93aa3889-fedc-4921-adc9-fd0ccdc5e9d8.png)

**Comment by laserbeak** [comment]
OOH! And another.
Looks like there's some truncation happening?
![image](https://user-images.githubusercontent.com/3384800/204152147-42c3d386-abd6-4c0d-b10f-7a3ba840c637.png)

**Comment by Badnoob-327** [comment]
and some pictures got pixelated out as well.

**Comment by nemgrea** [comment]
will be fixed via https://github.com/VoronDesign/Voron-Tap/pull/16
